### ISSUE TITLE
Journal bizarre

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#100]
Salut François,

J'ai ce journal qui apparait:

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/cd7c0eea-f9da-4cda-9734-c80e623bbdc3)

Est-ce un vrai?

**Comment by khameos** [comment]
Et oui c'est bien un "vrai", en tout cas c'est bien une donnée présente dans le fichier Excel de Damien et Julien :

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/c000b45e-1aea-4dd2-8aec-8f2dfd8918e0)

**Comment by EmilieVrot** [comment]
ok merci :)
