### ISSUE TITLE
Polices différentes entre Scientific Evidence et les autres modules

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#102]
Bonjour François,

Il y a des écarts de police entre scientific evidence et le reste de l'appli, par exemple:

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/951e9fb1-a3a0-41d5-8069-c54ed5bd7972)

J'en ai parlé avec Vizzuality et ils me conseillent de regarder du côté d ela redirection nginx. De veiller à ce que le FO accède bien aux 4 polices Roboto qui sont dans le folder assets 

Est-ce que tu peux vérifier si c'est déjà le cas?

Merci d'avance,

(pour suivi, ticket JIRA ORC-712)

**Comment by khameos** [comment]
Sur SE, j'utilise la même police que Vizzuality:

https://orcasa-review4c.vercel.app/
https://www.impact4soil.com/scientific-evidence/

sont bien identiques

Après je ne peux pas te répondre sur le reste de l'application

**Comment by EmilieVrot** [comment]
D'accord merci François
