### ISSUE TITLE
Scientific evidence - Display of the graphs

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#103]
Bonjour François:

Dans la visualisation des graphes, les catégories et les interventions devraient être en gras.
Cela ne s'affiche pas chez moi:

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/6b411fdc-b402-4b44-8db0-812089e1d0e8)

Côté Vizzuality cela s'affiche correctement:

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/48635124-624e-4595-9c02-9e1c66f9d24c)

Cela réagit comment de ton côté?

Merci

(Ticket JIRA pour référence: ORC-711)

**Comment by khameos** [comment]
Salut Emilie, c'est ok ce mon côté :

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/7dd36d84-9f26-46e9-b9fc-e960ec4bc547)

Aussi bien en prod qu'en pré-prod

**Comment by EmilieVrot** [comment]
ok merci

Vraiment bizarre que cela ne fonctionne pas de mon côté, même sur plusieurs navigateurs
