### ISSUE TITLE
Scientific evidence - Erreur dans le filtre

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#104]
Salut François,

Vizzuality me dit qu'ils ne peuvent pas corriger l'erreur sur le filtre que tu m'avais fait remonter :
- All / Publications : Filter / Year = 1910
- puis retour à la page d'accueil / sélection Other land” / Publications / Filter
- on voit alors toujours deux filtres sur la gauche et 1 à droite

Ils disent qu'ils ne peuvent pas accéder à ton code. si c'est le cas, est-ce que tu peux partager ton code sur le répertoire public du projet pour qu'ils puissent corriger ensuite?

Merci

(pour référence ticket JIRA ORC-716)

**Comment by EmilieVrot** [comment]
Salut François, 
Je reviens vers toi sur ce ticket?

**Comment by khameos** [comment]
Emilie, 

il n'y a aucun rapport avec mon code vu que je reproduis le bug sur leur plate-forme

**Comment by EmilieVrot** [comment]
Salut François, 

Vizzuality a livré un nouveau correctif pour ce bug.
C'est le dernier correctif qui restait sur Scientific evidence, il ne devrait pas y avoir d'autres livraisons pour ce module.

Quand tu auras du temps, pourras-tu le passer en production?

Merci

**Comment by khameos** [comment]
Salut Emilie, 

c'est sur la prod et le correctif fonctionne correctement

@+

**Comment by EmilieVrot** [comment]
Effectivement! Merci :)
