### ISSUE TITLE
Message pop up qui n'apparait pas sur la carte

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#108]
Bonjour François,

En cliquant sur le bouton Publications de Scientific Evidence et en ouvrant une carte pour la 1e fois, ce message en jaune devrait apparaitre:

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/789502c0-c85e-46db-9339-1736ea787931)

Peux-tu regarder de ton côté s'il y a une manip à faire?

Merci

**Comment by khameos** [comment]
Il manquait du code coté Vizzuality, j'ai corrigé 

Je livrerai avec les dernières nouveautés

**Comment by khameos** [comment]
Livré semaine dernière
