### ISSUE TITLE
When selecting one publication filter, sometimes all the values of the other filters become selected

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#13]

**Comment by clementprdhomme** [comment]
@EmilieVrot J'ai fait des tests et il semble que cela se passe uniquement quand l'utilisateur ferme le premier filter (“Publications type”) en cliquant à proximité du bouton “Reset all”. Est-ce que toi ou @khameos avez trouvé un autre cas?

**Comment by khameos** [comment]
@clementprdhomme ; je viens de vérifier

Le problème vient du fait que le "Reset All" prend en fait toute la largeur de la div ; c'est assez perturbant 

Peut-être en ajoutant une class btn-primary, ca serait moins gênant ?

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/33559076-1577-43bb-ba2a-313863e789e7)

Merci

**Comment by khameos** [comment]
ok
