### ISSUE TITLE
Map => Zoom out by default

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#16]
Show the whole world by default (or zoom out 3 notches) when opening the module (+ eventually reduce further the size of the sidebar)
The complaint here is that even on a 27-29” screen, the sidebar takes too much space compared to the map

**Comment by khameos** [comment]
ok

**Comment by EmilieVrot** [comment]
I would like to reopen this issue

When I click on the icon to hide the left bar, instead of enlarging the map, some zones are duplicated

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/a426e523-61d6-4e62-8ec5-256e0b9b385b)

**Comment by EmilieVrot** [comment]
I have discussed it with François and it is ok to leave it as it is. Thanks
