### ISSUE TITLE
[QA] Favicon 

### ISSUE THREAD

**Issue by khameos** [Orcasa-Platform/orcasa-review4c#24]
Is  a favicon provided ?

**Comment by carlabiscotti** [comment]
Hi Emilie, thanks for pointing this out. We still need to add this to the main application; when working on it, we can also work on a favicon for the Scientific application. Unless Francois can implement that on his own. Please let me know.

**Comment by carlabiscotti** [comment]
Hi Emilie and Francois, the Favicon is in place https://orcasa-review4c.vercel.app/

**Comment by EmilieVrot** [comment]
Thank you Carla. 
I leave it open to test it in the development environment when it will be delivered.

**Comment by EmilieVrot** [comment]
This one has been delivered
