### ISSUE TITLE
Urgent - Publication not found

### ISSUE THREAD

**Issue by khameos** [Orcasa-Platform/orcasa-review4c#44]
I click "Learn More" on a publication

Sometimes, it will not found it

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/2b7f0402-8940-4982-b708-9a65b37c36c5)

ID is null :

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/0ce17ac3-1624-45f0-9143-dea8d9a68919)

I have the same behavior on my platform

**Comment by khameos** [comment]
It seems it's since this commit (dynamic-data.js)
https://github.com/Orcasa-Platform/orcasa-review4c/commit/2feacbac8ba8eeeb1dd6cd6d213e7025c8f178b9

If I change the Learn More button on my platform, it's OK for me !

**Comment by clementprdhomme** [comment]
@khameos Fixed! Sorry about this.

**Comment by khameos** [comment]
Thanks it's ok !
