### ISSUE TITLE
Comparaison chiffres des filtres à gauche et sur la carte

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#47]
Bonjour François,

Les chiffres des filtres à gauche ne correspondent pas aux totaux indiqués sur la carte:
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/e5107aca-c166-4cbc-814c-983850caf607)

Est-ce que tu sais pourquoi?

**Comment by khameos** [comment]
Sur la carte, j'affiche le nombre d'effect size (comme sur review4c.net)
tandis que sur les graphs, le nombre de données liées ( = les publications scientifiques, soit le nombre que tu retrouves quand tu cliques sur publications)

Du coup, je mets aussi le nombre d'effect size sur chaque intervention des graphs ?

**Comment by EmilieVrot** [comment]
Je vais voir ça avec Damien pour voir si c'est bien ce qu'il souhaite. Je pense que oui, mais dans ce cas, il faudra changer la légende de la carte.
Je te tiendrai au courant de sa réponse.

**Comment by EmilieVrot** [comment]
Bonjour François,

Voici ce qui me gêne:

si je prends "Other land", on me dit 1145 publications:
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/ae5ba390-ae41-4288-8743-55b5d067c899)

 
quand je clique pour aller voir la liste des publis, c'est bien 1145 aussi:
 
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/314ecf90-f7f9-419c-a86b-89133d632fa8)


par contre sur la carte j'en ai bien plus que 1145:
 
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/fb00d30e-3e97-4740-8b6a-b3e0ed3646dd)


et sur les graphes, le total de fait pas 1145:
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/ab1fbfb2-783a-4dc7-8e53-6537e7790f3d)

 

alors que si je clique sur le 80 de fire, on me fait comprendre que c'est 80 publications:
 
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/f78a120c-a3f5-428c-b48d-454fac0a93bb)

J'ai commencé à en parler avec Damien mais il rentrait en réunion.
Serais-tu dispo pour qu'on regarde demain vers 15h?

Merci,
Emilie

**Comment by khameos** [comment]
Voilà ce que j'ai d'après le fichier Data_Base_C_Sol_DATAVERSE_2022-05-04 :

Dans l'onglet effect_size : 

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/6ca8fe6b-11a5-41bb-b003-538a6f2d120c)

Donc pour otherland -> fire : 1 MA "489_Pellegrini et al, 2018"

Ensuite dans l'onglet Primary sytudies : je récupère 93 Primary studies liées à cette méta-analyse

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/58d0830e-6908-421f-8be8-9d64e4874efd)


Je supprime certaines (doublons, données manquantes) 
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/a3cdeddd-736f-4ba1-aa4b-7f54aaee2693)


Et je tombe bien à 80

**Comment by EmilieVrot** [comment]
Merci effectivement cela fonctionne bien!

Et pour ces deux points là qu'en penses-tu?
- et à droite des graphes, le total ne fait pas 1145 (alors que si je clique sur le 80 de fire, on me fait comprendre que c'est 80 publications)
- sur la carte j'en ai bien plus que 1145

**Comment by khameos** [comment]
Entre les parenthèses, j'affiche les nombres de publications scientifiques tandis que sur la carte, je mets le nombre d'effect-size liées a ces publications. C'était le comportement sur R4C que j'ai gardé ici mais qui semble confusant

Je peux modifier mon script si besoin en affichant sur la carte les publications.
 ATTENTION, le nombre entre les parenthèses ne correspondra pas forcément vu qu'une publication peut être dans plusieurs pays à la fois !

**Comment by khameos** [comment]
Petite précision concernant ce que j'ai dit plus haut :
_le nombre entre les parenthèses ne correspondra pas forcément vu qu'une publication peut être dans plusieurs pays à la fois !_

si on reprend l'exemple de OtherLand > Fire où il y a 80 publications

Parmi ces publications, j'en ai une 30aine qui n'ont pas de pays =>

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/bdc792dd-42f4-4347-8284-c159c857de11)

Donc le chiffre sur la colonne de gauche sera toujours plus grand que les nombre de points sur la carto (environ 10% des publications sont sans pays)

**Comment by EmilieVrot** [comment]
Merci François pour la précision.

**Comment by EmilieVrot** [comment]
Bonjour François, juste pour être sûre, sur la carte tu affiches bien le nombre de publications (primary studies) mais cela n'inclut pas les méta-analyses?

**Comment by EmilieVrot** [comment]
Merci François, oui c'était bien lié au ticket 58

Bonne journée
