### ISSUE TITLE
Taille des modules

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#48]
Bonjour François,

Il y a un écart de taille des textes et des modules quand j'ouvre Scientific evidence ou les autres modules de Vizzuality (https://demo.orcasa.dev-vizzuality.com/network?map-settings=%7B%22labels%22%3Anull%2C%22basemap%22%3A%22basemap-relief%22%7D&bbox=%5B-160.74%2C-80%2C160.74%2C85.05%5D).

Est-ce mon zoom que je dois régler ou est-ce que tu peux t'ajuster pour diminuer le zoom de ton côté?

Merci,
Emilie

**Comment by EmilieVrot** [comment]
En fait j'ai l'impression que scientific evidence est plus "zoomé" par défaut que les modules développés par Vizzuality:

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/f5da0e97-a32a-43cb-8d96-e4443a074be3)

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/d8fde7f1-3f1a-4a2e-b777-e48d68c63f0e)

**Comment by khameos** [comment]
Si je compare http://ns3192284.ip-5-39-73.eu/scientific_evidence/ avec https://orcasa-review4c.vercel.app/ , j'ai les mêmes tailles de texte/modules.

Du coup, le problème viendrait plus du fait d'unifier les différents styles entre les plates-formes ?

**Comment by EmilieVrot** [comment]
vu ensemble, je ferme ce ticket
