### ISSUE TITLE
[To do] Map disappear after zooming out 12 times

### ISSUE THREAD

**Issue by khameos** [Orcasa-Platform/orcasa-review4c#49]
Deux petites questions pour savoir si vous reproduisez les comportements ( Emilie n'a pas les mêmes résultats)

1) Sur la map de base (celle sélectionnée au chargement), je clique sur le "+" 12/13 fois, j'ai la carto qui disparaît :

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/4ab71797-66c0-4fba-b22d-a73fb8d4f019)

2) Au départ le "-" de zoom est grisé, je zoome une fois et dézoome. Il n'est plus grisé : 

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/5717052/c7f17b9c-8302-4e21-a68e-c5382e486632)

Personnellement, je reproduis sur Firefox et Chrome
Merci

**Comment by clementprdhomme** [comment]
Salut François,

Pour le premier point, je confirme que les tiles disparaissent après avoir dézoomé 12 fois. On peut probablement limité le zoom avant.

Pour le second point, le bouton ne m’apparaît pas grisé par défaut quand j'ouvre le module. Par contre, quand je suis au zoom minimum et je clique dessus, il est effectivement grisé durant 1 seconde peut-être et ensuite revient à sa couleur initiale. Je me demande si ce n'est pas lié à un problème d'arrondi vu que MapLibre supporte un niveau de zoom continu.

Je pense qu'on peut garder cette issue ouverte pour que l'on règle ces soucis dans le future.

Merci !

**Comment by EmilieVrot** [comment]
JIRA #ORC-423
