### ISSUE TITLE
[In progress] Scientific Evidence - Text change in "Methodology"page

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#52]
In the Methodology, we should add these information:

- A publication can be linked to two countries (that's why we can have more publications on the map)
- All the subcategories are not displayed

**Comment by carlabiscotti** [comment]
Hi Emilie, 

Sure, I believe the text explaining the Methodology was created by you. How do you want to integrate this?

The first point makes sense to me. I don't understand what the second item refers to, would you mind clarifying this to me? Thanks.

Here is the design of the Methodology part for our reference: https://www.figma.com/proto/DBXFTLd6nFBmg6fFE6P2cX/ORCaSa-Design-%5BInternal%5D?type=design&node-id=527-21827&t=UsPRalqwTxAHwpPm-0&scaling=min-zoom&page-id=165%3A38016&starting-point-node-id=3066%3A18940&show-proto-sidebar=1

**Comment by carlabiscotti** [comment]
I will confirm in which sprint we can address this in the upcoming days.

**Comment by carlabiscotti** [comment]
Thank you Emilie.

When saying "only the most relevant subcategories are displayed." do you think we could mention somehow the criteria used to select the "relevant" subcategories? I think this could add value to users by letting them better understand.

Please notice this will be addressed after finishing the practices module.

**Comment by EmilieVrot** [comment]
Hello Carla,

What is not displayed: the categories "others" , and the complex categories (for instance combination of several interventions).

Maybe we can say it this way:
"A few subcategories, complex or not precisely defined, are not displayed in the graphs"

**Comment by carlabiscotti** [comment]
Hi Emilie, this should be ready in staging.

**Comment by EmilieVrot** [comment]
Hello carla, 

I don't see this text in staging:

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/e1c1eef5-112a-4b5a-a849-bbd4c69e6d04)
![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/9c34c918-6048-4cbd-be15-880633a8fd2b)

**Comment by clementprdhomme** [comment]
Hello Emilie,

Please see the change at this address instead: https://orcasa-review4c.vercel.app/.

If you don't have any more feedback, we can ask François to port the changes to the other address http://ns3192284.ip-5-39-73.eu/.
