### ISSUE TITLE
[QA] Scientific Evidence - Adjustments to the methodology page

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#58]
Hello Carla,

I am just writing here what I sent you by email on wesnesday (I am putting Alvaro in cc):

-	Text modifications:
o	Soil organic Carbon --> Soil Organic Carbon
o	We extracted all quantifications (with an “s”)  
o	In the legend: 'sum of publication.' -> "Number of primary studies"

-	On the graph, set up a y-axis scale 

-	In the related scientific work, add this one: [View article (google.com)](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=vge-xGEAAAAJ&citation_for_view=vge-xGEAAAAJ:738O_yMBCRsC)

-	It looks like there is some text at the bottom that I cannot read completly :

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/10dfe37d-9379-4b5f-b95d-1b8a9da0b7c6)

Best,
Emilie

**Comment by Bluesmile82** [comment]
Hi @EmilieVrot,

About the change suggestion: In the legend: 'sum of publication.' -> "Number of primary studies"

In the map we are showing both primary and metanalyses, so wouldn't it make sense to keep on the legend the 'sum of publication' text?

**Comment by EmilieVrot** [comment]
Hello Alvaro,

In fact we are displaying only primary studies on the map. Meta analyses do not have a country.
You can keep "Number of promary studies".

Thanks

**Comment by carlabiscotti** [comment]
Hi Emilie, 
We discussed this text change internally. We concluded that we should rename to "primary studies" in several places (highlighted below), could you please confirm this is correct? Thanks. 
![image-20240117-115316](https://github.com/Orcasa-Platform/orcasa-review4c/assets/97748487/369f277d-1e04-4bf5-bee2-90846617e7bb)
![image-20240117-115157](https://github.com/Orcasa-Platform/orcasa-review4c/assets/97748487/10e9a8fd-5a15-45cd-9a5c-4484b6deb3aa)

**Comment by carlabiscotti** [comment]
Hi Emilie, The methodology page is now implemented and ready for your review here: https://orcasa-review4c.vercel.app/ 

The only change pending is the change you requested  "In the legend: 'sum of publication.' -> "Number of primary studies"". We are pending on your response to my previous comment to proceed.

**Comment by EmilieVrot** [comment]
Hello Carla,

Sorry for my late reply. Yes you can make the text cahnges you mentioned.

Thanks

**Comment by clementprdhomme** [comment]
Hello Emilie,

I think we've finished to address all your feedback about this module. Could you please review https://orcasa-review4c.vercel.app/?

Regarding why you're not seeing the Methodology page, it's because you're using the Cirad version of the page (http://ns3192284.ip-5-39-73.eu/orcasa/). Please open https://orcasa-review4c.vercel.app/ instead.

If you're happy with all the changes, then we can ask François to port the changes to the Cirad version of the page.

**Comment by EmilieVrot** [comment]
Hello Clement,

Yes everything is fine on this page.

François already integrated it to the Cirad version.

Best,
Emilie
