### ISSUE TITLE
Page d'accueil - Compteur automatique des méta analyses

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#62]
Bonjour François,

Sur la page d'accueil de la plateforme, il y a un compteur automatique des méta analyses. 

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/9bf203cd-74ae-4a16-a906-406c8a2fe0fd)

Est-ce que tu pourrais mettre à dispo de Vizzuality cette info pour éviter de la saisir manuellement?
Si oui, sous quelle forme (API ou autre)?

Merci

**Comment by khameos** [comment]
Bonjour Emilie,

sur scientific, j'ai déjà cette donnée générée.

Il leur suffit d'appeler :
http://ns3192284.ip-5-39-73.eu/scientific_evidence/mocks/data/charts/index.json

> all > metaAnalysis  pour avoir le bon nombre

**Comment by EmilieVrot** [comment]
Super merci François!
