### ISSUE TITLE
Recherche par mots clés

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#70]
Salut François,

Sur quel contenu porte la recherche par mot clé dans le FO de Scientific Evidence?
Cela ne fonctionne pas sur les auteurs. cela pourrait être bien de l'ajouter.
Peux-tu le faire de ton côté ou je dois demander à Vizzuality?

Merci

**Comment by khameos** [comment]
Salut, 

pour le moment, je ne fais le recherche que sur Titre + abstract.

J'ajoute les auteurs à la recherche dès que possible !

**Comment by EmilieVrot** [comment]
Super merci François!

**Comment by EmilieVrot** [comment]
Merci cela fonctionne bien :)
