### ISSUE TITLE
Intégrer les stats de fréquentation du FO de scientific evidence

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#72]
Salut François,

A fin que l'on puisse comptabiliser les stats de fréquentation du FO de scientific evidence, peux-tu intégrer le script js matomo ci-dessous dans le Front Office de prod (-	impact.4soil.com/scientific-evidence) ?

L’identifiant est : 149

Voici le code javascript :

<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://matomo.cirad.fr/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '149']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

https://developer.matomo.org/guides/tracking-javascript-guide
 
N'hésite pas s'il te faut plus d'infos!

Merci,
Emilie

**Comment by EmilieVrot** [comment]
Salut François,

Une petite relance sur cette demande.

Merci à toi!
Emilie

**Comment by khameos** [comment]
Oups désolé, j'étais passé au travers.

C'est en ligne !
