### ISSUE TITLE
Redesign de Scientific evidence

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#88]
Bonjour François,

Suite à notre discussion d’hier sur le nouveau design de scientific evidence, je voulais voir quelques points avec toi :

1.	Pour que l’on puisse tester la carte, tu proposais de la mettre sur la version de démo ([Impact4Soil - Scientific evidence (orcasa-review4c.vercel.app)](https://orcasa-review4c.vercel.app/),). Est-ce que tu auras le temps de le faire pour que l'on puisse la tester s'il y a des corrections à apporter par Vizzuality? Il faut pour cela créer un fichier env.js file à la racine du module qui contient le token pour le compte Mapbox. Les instructions sont là: [orcasa/CHANGELOG.md at main · Orcasa-Platform/orcasa](https://github.com/Orcasa-Platform/orcasa/blob/main/CHANGELOG.md#v9)

2.	Dans la version actuelle, j’ai l’impression que les filtres ne se mettent pas à jour en fonction des valeurs sélectionnées sur un autre filtre. Je pense que j’ai mal compris ce que tu voulais dire hier à ce sujet.

3.	 Concernant les nouveaux filtres main intervention, intervention et subtype, voici ce que me répond Vizzuality:

D'après ce que je peux voir, nous n'avons pas modifié la structure des données depuis les 8 derniers mois, donc si la version précédente du module fonctionnait bien, je ne vois aucune raison pour laquelle nous ne pourrions pas fournir ces filtres. Par exemple, les noms des principales interventions pour les terres agricoles proviennent des fichiers :
- /data/charts/cropland/climate-change/index.json
- /data/charts/cropland/land-use/index.json
- /data/charts/cropland/management/index.json
Ensuite, si l'utilisateur filtre par Changement climatique, nous chargerions le fichier  /data/publications/cropland/climate-change/index.json.
Comme vous pouvez le constater, il s'agit de la même structure qu'auparavant. Aucune modification n'est nécessaire de votre côté.

Si c’est plus simple, on peut aussi s’appeler 5 min sur ces 3 sujets.

Merci à toi,
Emilie

**Comment by EmilieVrot** [comment]
Ce dernier point fonctionne, je pense que l'on peut fermer ce ticket?

**Comment by khameos** [comment]
Ok de mon côté
