### ISSUE TITLE
Webservice pour appli tierce

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#93]
Bonjour François,

Avec Julien, nous travaillons sur un autre projet européen (Soilwise) qui peut être intéressé à réutiliser certaines données produites par Impact4Soil. 
Nous n'en avions pas parlé avant, mais je me demandais s'il existe déjà pour Review4C/Scientific evidence une possibilité pour des outils externes de récupérer ces données (webservice, serveur ftp, etc.)? ou est-ce quelque chose que l'on peut envisager par la suite?

Merci,
Emilie

**Comment by khameos** [comment]
On a déjà des webservices qui existent.

Après, tout dépend des données que vous voulez, on peut probablement ajouter des services pour cela

**Comment by EmilieVrot** [comment]
Merci François. Pour l'instant ce n'est pas définit sur le projet. Ils sont en train de collecter les infos dispo qui pourraient être intéressantes sur cette plateforme.
Sur tes webservices, y a-t-il des restrictions particulières (de sécurité ou autre)?

**Comment by khameos** [comment]
Normalement pas de problème vu que c'est de notre côté qu'on leur fournira de la donnée.
(un peu comme le webservice que je fournis à Vizzuality pour afficher le nombre de métas)

**Comment by EmilieVrot** [comment]
ok c'est noté merci !
On verra ça au moment voulu, quand j'aurai plus d'infos.

Merci!
