### ISSUE TITLE
Filtre non détecté

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa-review4c#97]
J’ai sélectionné 3 filtres mais seulement 2 sont affichés sur la gauche :

![image](https://github.com/Orcasa-Platform/orcasa-review4c/assets/139888940/e1828700-d025-49f2-aac4-26c38ebf39a5)

 
J’ai vu avec Vizzuality et ils me disent qu’il faut faire un changement dans la fonction recalculateActiveFilters.

Il faut remplacer cette ligne :

const filtersActiveNumber = window.getters.activeFilters().length;// + landUseFiltersCount;

Par celle-ci :

const filtersActiveNumber = window.getters.activeFilters().length + landUseFiltersCount;

Tu peux regarder de ton côté ?

**Comment by khameos** [comment]
J'avais commenté cette partie de code vu que l'on cachait les interventions.

J'ai corrigé la fonction de calcul pour prendre en compte uniquement les land use !

**Comment by EmilieVrot** [comment]
Merci c'est ok pour moi !
